### ISSUE TITLE
Played videos in Geltarapp appear in the client-side user’s listening history

### ISSUE THREAD

**Issue by Voraksis** [salierri/geltara#19] opened 2020-04-25 10:28 UTC
**Project**: Geltarapp
**Product**: Geltarapp Client Side
**Version**: Unknown (probably most recent)

**Severity**: Minor (S3) – has a workaround

**Description**
After the recent DnD session we had I have noticed that the videos from the Geltarapp appeared in my YouTube listening history. And unfortunately, they are affecting my recommendations in YouTube. 

**Repro Steps**
Nothing special, just join a session and listen something.

**Workaround:**
The user shall use their browser in incognito mode.

**Comment by salierri** [comment] 2020-04-28 16:28
The issue is fixed on [fix/youtube-history](https://github.com/salierri/geltarapp/tree/fix/youtube-history).
The fix will go live with the next weekly release.

**Closed as completed** 2020-04-30 16:29 UTC
